### ISSUE TITLE
Bug on line 376

### ISSUE THREAD

**Issue by Skyb0rg007** [zbyrn/pretty-expressive-sml#1]
Looks like you're shadowing the variable `d`, so if you try to flatten a `Cost` and it's already flat, you remove the cost.

**Comment by sorawee** [comment]
I made this mistake in the reference implementation at https://github.com/sorawee/pretty-expressive-ocaml/blob/main/lib/printer.ml too! Thanks for the report :)

**Comment by Skyb0rg007** [comment]
I think you also forgot to add `blank` to the signature / .mli file

**Comment by zbyrn** [comment]
Fixed!
